# Generated by Django 4.1 on 2026-08-07 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=225)),
                ('location', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('manager_name', models.CharField(max_length=225)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.owner')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=225)),
                ('phone', models.ImageField(max_length=225, upload_to='')),
                ('email', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.owner')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=225)),
                ('brand', models.CharField(max_length=225)),
                ('price', models.CharField(max_length=225)),
                ('stock', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('image', models.ImageField(max_length=225, upload_to='')),
                ('expiry_date', models.CharField(max_length=225)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.CharField(max_length=225)),
                ('payment_mode', models.CharField(max_length=225)),
                ('bill_number', models.CharField(max_length=225)),
                ('sales_date', models.CharField(max_length=225)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('photo', models.ImageField(max_length=225, upload_to='')),
                ('gender', models.CharField(max_length=225)),
                ('age', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('joining_date', models.CharField(max_length=225)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.branch')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='sales_details',
            fields=[
                ('sales_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=225)),
                ('unit_price', models.CharField(max_length=225)),
                ('sub_total_amount', models.CharField(max_length=225)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.product')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.sales')),
            ],
        ),
        migrations.AddField(
            model_name='sales',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.staff'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.product_category'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.owner'),
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('reply', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.login')),
            ],
        ),
    ]
